const fs=require('fs');
const read=f=>fs.readFileSync('src/'+f,'utf8');
let html=read('shell.html');
const put=(tag,content)=>{ html=html.replace('/*__'+tag+'__*/',()=>content); };
put('CSS',read('style.css'));
put('CONFIG',read('config.js'));
put('SIM',read('sim.js'));
put('RENDER',read('render.js'));
put('INPUT',read('input.js'));
put('UI',read('ui.js'));
put('MAIN',read('main.js'));
fs.mkdirSync('dist',{recursive:true});
fs.writeFileSync('dist/index.html',html);
console.log('built dist/index.html '+(html.length/1024).toFixed(0)+' KB');
